@host = localhost:8080

POST http://{{host}}/signup HTTP/1.1
content-type: application/json

{
    "firstName": "test-firstName",
    "lastName": "test-lastName",
    "email": "test-email",
    "password": "test-password"
}

###

POST http://{{host}}/signup HTTP/1.1
content-type: application/json

{
    "firstName": "test-firstName2",
    "lastName": "test-lastName2",
    "email": "test-email2",
    "password": "test-password2"
}

###

POST http://{{host}}/signup HTTP/1.1
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "johndoe@where.com",
    "password": "qwert"
}

###

GET http://{{host}}/users
content-type: application/json
