@host = localhost:8080

POST http://{{host}}/api/signup HTTP/1.1
content-type: application/json

{
    "firstName": "test-firstName",
    "lastName": "test-lastName",
    "email": "test-email",
    "password": "test-password"
}

###

POST http://{{host}}/api/signup HTTP/1.1
content-type: application/json

{
    "firstName": "test-firstName2",
    "lastName": "test-lastName2",
    "email": "test-email2",
    "password": "test-password2"
}

###

POST http://{{host}}/api/signup HTTP/1.1
content-type: application/json

{
    "firstName": "encryptionTest2-firstname",
    "lastName": "encryptionTest2-lastname",
    "email": "encryptionTest2-email",
    "password": "asdfg"
}

###

POST http://{{host}}/api/signup HTTP/1.1
content-type: application/json

{
    "firstName": "encryptionTest3-firstname",
    "lastName": "encryptionTest3-lastname",
    "email": "encryptionTest3-email",
    "password": "12345"
}

###

POST http://{{host}}/api/signup HTTP/1.1
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "johndoe@where.com",
    "password": "qwert"
}

###
POST http://{{host}}/api/signup HTTP/1.1
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "johndoe@gmail.com",
    "password": "qwert"
}

###
POST http://{{host}}/api/signup HTTP/1.1
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "johndoe@icloud.com",
    "password": "qwert"
}

###

GET http://{{host}}/api/users
content-type: application/json

###

POST http://{{host}}/api/login HTTP/1.1
content-type: application/json

{
    "email": "encryptionTest3-email",
    "password": "12345"
}

###

GET http://{{host}}/api/user
content-type: application/json

###
POST http://{{host}}/api/transaction
content-type: application/json

{
    "amount": 1000.00,
    "name": "Wal-Mart",
    "date": "12/23/2022",
    "category": "Groceries",
    "description": "Bought food for the week"
}

###
POST http://{{host}}/api/login
content-type: application/json

{
    "email": "test-email",
    "password": "test-password"
}

###
GET http://{{host}}/api/transaction
content-type: application/json

###
PUT http://{{host}}/api/transaction
content-type: application/json

{
    "data": {
        "userId": 35,
        "transactionId": 31,
        "amount": 1200,
        "name": "Publix",
        "date": "12/23/2022",
        "category": "Groceries",
        "description": "Bought food for the week"
    }
}

###
DELETE http://{{host}}/api/transaction/1
content-type: application/json

###
POST http://{{host}}/api/transaction
content-type: application/json

{
    "data": {
            "amount": 10,
            "name": "test2",
            "date": "12/25/2022",
            "category": "School",
            "description": "Textbook"
    }
}

###
POST http://{{host}}/api/budget
content-type: application/json

{
    "category": "food",
    "amountLimit": 50.5,
    "frequency": "Weekly",
    "duration": 2,
    "count":1,
    "startDate": "12/23/2022"
}

###
GET http://{{host}}/api/budget
content-type: application/json

###
GET http://{{host}}/api/deleted_budgets
content_type: application/json

###

PUT http://{{host}}/api/budget
content-type: application/json

 {
    "userId": 68,
    "budgetId": 1,
    "isDeleted": false,
    "data": {
        "category": "fast food",
        "amountLimit": 50.5,
        "frequency": "Weekly",
        "duration": 2,
        "count":1,
        "startDate:": "12/23/2022"
    }
 }

###

DELETE http://{{host}}/api/budget/22
content-type: application/json

###

DELETE http://{{host}}/api/delete-user
content-type: application/json

###
POST http://{{host}}/api/login
content-type: application/json

{
    "email": "joe@joe.com",
    "password": "qwert"
}
